import type { OnboardingBill } from './onboarding-bills';
export type BillOccurrenceStatus = 'upcoming'|'paid'|'overdue'|'skipped'|'partial';
export type BillOccurrence = { id:string; userId:string; billId:string; dueDate:string; expectedAmount:number; status:BillOccurrenceStatus; paidAt:string|null; paidAmount:number|null; transactionId:string|null };
export type OccurrenceDraft = Pick<BillOccurrence,'userId'|'billId'|'dueDate'|'expectedAmount'|'status'>;
const iso=(date:Date)=>date.toISOString().slice(0,10); const atNoon=(value:string)=>new Date(`${value}T12:00:00`);
function safeDay(year:number,month:number,day:number){return new Date(year,month,Math.min(Math.max(1,day),new Date(year,month+1,0).getDate()),12)}
export function occurrenceDates(bill:OnboardingBill,today=new Date()){const y=today.getFullYear(),m=today.getMonth();if(bill.frequency==='weekly'){const target=(Math.max(1,bill.dueDay)-1)%7,current=new Date(y,m,today.getDate(),12);current.setDate(current.getDate()-((current.getDay()-target+7)%7));const next=new Date(current);next.setDate(next.getDate()+7);return[iso(current),iso(next)]}if(bill.frequency==='annual'){const current=safeDay(y,m,bill.dueDay),next=safeDay(y+1,m,bill.dueDay);return[iso(current),iso(next)]}if(bill.frequency==='quarterly'){const current=safeDay(y,m,bill.dueDay),next=safeDay(y,m+3,bill.dueDay);return[iso(current),iso(next)]}return[iso(safeDay(y,m,bill.dueDay)),iso(safeDay(y,m+1,bill.dueDay))]}
export function occurrenceDrafts(userId:string,bills:OnboardingBill[],today=new Date()){const seen=new Set<string>();return bills.flatMap(b=>occurrenceDates(b,today).map(d=>({userId,billId:b.id,dueDate:d,expectedAmount:b.amount,status:'upcoming' as const}))).filter(item=>{const key=`${item.userId}:${item.billId}:${item.dueDate}`;if(seen.has(key))return false;seen.add(key);return true})}
export function effectiveStatus(o:BillOccurrence,today=new Date()):BillOccurrenceStatus{if(o.status==='paid'||o.status==='skipped')return o.status;if(o.status==='partial')return (o.paidAmount??0)>=o.expectedAmount?'paid':iso(atNoon(o.dueDate))<iso(today)?'overdue':'partial';return iso(atNoon(o.dueDate))<iso(today)?'overdue':'upcoming'}
export function isResolved(o:BillOccurrence){return o.status==='paid'||o.status==='skipped'||(o.status==='partial'&&(o.paidAmount??0)>=o.expectedAmount)}
export function activeOccurrences(items:BillOccurrence[],today=new Date()){return items.filter(o=>!isResolved(o)&&['upcoming','overdue','partial'].includes(effectiveStatus(o,today)))}
export function markPaid(o:BillOccurrence,amount=o.expectedAmount,date=iso(new Date())):BillOccurrence{return{...o,status:amount>=o.expectedAmount?'paid':'partial',paidAmount:amount,paidAt:`${date}T12:00:00.000Z`}}
export function undoPayment(o:BillOccurrence):BillOccurrence{return{...o,status:'upcoming',paidAmount:null,paidAt:null}}
export function skipOccurrence(o:BillOccurrence):BillOccurrence{return{...o,status:'skipped',paidAmount:null,paidAt:null}}
