import { notFound } from 'next/navigation';
import { APP_VERSION } from '@/lib/version';
import { createClient } from '@/lib/supabase/server';
import { LATEST_SCHEMA_VERSION,MIGRATIONS,REQUIRED_SCHEMA,missingMigrations,type Probe } from '@/lib/system-health';

export const dynamic = 'force-dynamic';
export default async function SystemHealthPage(){
  if(process.env.NODE_ENV!=='development')notFound();
  const probes:Probe[]=[];let connected=false;let connectionDetail='Not configured';
  try{const client=await createClient();const{error:authError}=await client.auth.getSession();connected=!authError;connectionDetail=authError?.message??'Connected';for(const[table,columns]of Object.entries(REQUIRED_SCHEMA)){const{error}=await client.from(table).select(columns.join(',')).limit(1);probes.push({table,ok:!error,error:error?.message})}}catch(error){connectionDetail=error instanceof Error?error.message:'Connection failed';for(const table of Object.keys(REQUIRED_SCHEMA))probes.push({table,ok:false,error:connectionDetail})}
  const missing=missingMigrations(probes),healthy=connected&&probes.every(probe=>probe.ok);const detectedVersion=probes.find(probe=>probe.table==='bill_occurrences')?.ok?LATEST_SCHEMA_VERSION:'Pre-011 or incomplete';
  const flags=[['Bill occurrence tracking',probes.find(p=>p.table==='bill_occurrences')?.ok],['Reviewed transaction posting',probes.find(p=>p.table==='transactions')?.ok],['Recommendation history',probes.find(p=>p.table==='pilot_recommendation_history')?.ok],['Promotional debt support',probes.find(p=>p.table==='debts')?.ok]] as const;
  return <main className="mx-auto max-w-6xl px-5 py-8 text-slate-100"><p className="text-sm font-semibold text-cyan-300">Developer tools</p><h1 className="mt-2 text-4xl font-semibold">System Health</h1><p className="mt-2 text-slate-400">Read-only development diagnostics. This route returns 404 outside development.</p><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Application version" value={APP_VERSION}/><Metric label="Environment" value={process.env.NODE_ENV}/><Metric label="Database schema version" value={detectedVersion}/><Metric label="Overall status" value={healthy?'Healthy':'Attention required'} ok={healthy}/></section><section className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Supabase connection"><Status ok={connected} label={connectionDetail}/></Panel><Panel title="Migration status"><p className="text-sm text-slate-400">Target: {LATEST_SCHEMA_VERSION} · {MIGRATIONS.length} tracked files</p><div className="mt-3"><Status ok={missing.length===0} label={missing.length===0?'No missing migrations inferred':`${missing.length} missing or incomplete`}/></div></Panel><Panel title="Required tables and columns"><div className="space-y-3">{probes.map(probe=><div key={probe.table} className="rounded-xl border border-slate-800 p-3"><Status ok={probe.ok} label={probe.table}/><p className="mt-2 break-words text-xs text-slate-500">{REQUIRED_SCHEMA[probe.table as keyof typeof REQUIRED_SCHEMA].join(', ')}</p>{probe.error&&<p className="mt-2 break-words text-xs text-rose-300">{probe.error}</p>}</div>)}</div></Panel><Panel title="Missing migrations">{missing.length?<ul className="space-y-2 text-sm text-rose-300">{missing.map(item=><li key={item}>{item}</li>)}</ul>:<Status ok label="None detected"/>}</Panel><Panel title="Feature flags"><div className="space-y-3">{flags.map(([label,on])=><Status key={label} ok={Boolean(on)} label={`${label}: ${on?'enabled':'disabled'}`}/>)}</div></Panel></section></main>;
}
function Metric({label,value,ok}:{label:string;value:string;ok?:boolean}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-500">{label}</p><p className={`mt-2 font-semibold ${ok===false?'text-rose-300':''}`}>{value}</p></div>}function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="mb-4 text-xl font-semibold">{title}</h2>{children}</section>}function Status({ok,label}:{ok:boolean;label:string}){return <div className="flex items-center gap-2 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${ok?'bg-emerald-400':'bg-rose-400'}`}/><span>{label}</span></div>}
