'use client';
import { useEffect,useState } from 'react';
import { createClient } from '@/lib/supabase';
import { occurrenceDrafts,effectiveStatus,markPaid,type BillOccurrence } from '@/lib/bill-occurrences';
type Bill={id:string;name:string;amount:number;dueDay:number;frequency:string};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}),today=()=>new Date().toISOString().slice(0,10);
const map=(r:Record<string,unknown>):BillOccurrence=>({id:String(r.id),userId:String(r.user_id),billId:String(r.bill_id),dueDate:String(r.due_date),expectedAmount:Number(r.expected_amount),status:r.status as BillOccurrence['status'],paidAt:r.paid_at?String(r.paid_at):null,paidAmount:r.paid_amount==null?null:Number(r.paid_amount),transactionId:r.transaction_id?String(r.transaction_id):null});
export default function BillsPage(){
 const[bills,setBills]=useState<Bill[]>([]),[items,setItems]=useState<BillOccurrence[]>([]),[userId,setUserId]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[dialog,setDialog]=useState<{item:BillOccurrence;amount:number;date:string;partial:boolean}|null>(null);
 async function refresh(s:NonNullable<ReturnType<typeof createClient>>,u:string,loaded:Bill[]){const drafts=occurrenceDrafts(u,loaded);if(drafts.length)await s.from('bill_occurrences').upsert(drafts.map(d=>({user_id:d.userId,bill_id:d.billId,due_date:d.dueDate,expected_amount:d.expectedAmount,status:d.status})),{onConflict:'user_id,bill_id,due_date',ignoreDuplicates:true});const{data,error}=await s.from('bill_occurrences').select('*').eq('user_id',u).order('due_date');if(error)setMessage('Bill tracking requires the bill-occurrence migration.');else setItems((data??[]).map(map))}
 useEffect(()=>{const s=createClient();if(!s){setLoading(false);return}void(async()=>{const{data:{user}}=await s.auth.getUser();if(!user)return window.location.assign('/login');setUserId(user.id);const{data,error}=await s.from('bills').select('*').eq('user_id',user.id).order('due_day');if(error)setMessage('We couldn’t load your bills.');else{const loaded=(data??[]).map(r=>({id:r.id,name:r.name,amount:Number(r.amount),dueDay:Number(r.due_day),frequency:r.frequency}));setBills(loaded);await refresh(s,user.id,loaded)}setLoading(false)})()},[]);
 async function change(item:BillOccurrence,changes:Record<string,unknown>,success:string){const s=createClient();if(!s)return;const{error}=await s.from('bill_occurrences').update({...changes,updated_at:new Date().toISOString()}).eq('id',item.id).eq('user_id',userId);if(error)return setMessage('We couldn’t update this occurrence.');setItems(list=>list.map(x=>x.id===item.id?{...x,status:(changes.status??x.status) as BillOccurrence['status'],paidAt:changes.paid_at===null?null:String(changes.paid_at??x.paidAt),paidAmount:changes.paid_amount===null?null:Number(changes.paid_amount??x.paidAmount)}:x));setMessage(success)}
 async function submit(){if(!dialog)return;const paid=markPaid(dialog.item,dialog.amount,dialog.date);await change(dialog.item,{status:dialog.partial&&dialog.amount<dialog.item.expectedAmount?'partial':paid.status,paid_amount:dialog.amount,paid_at:paid.paidAt},dialog.partial?'Partial payment recorded.':'Bill marked paid.');setDialog(null)}
 async function saveBills(){const s=createClient();if(!s)return;for(const bill of bills){const{error}=await s.from('bills').upsert({id:bill.id,user_id:userId,name:bill.name.trim(),amount:Math.max(0,bill.amount),due_day:bill.dueDay,frequency:bill.frequency},{onConflict:'id'});if(error)return setMessage(`We couldn’t save ${bill.name||'this bill'}.`)}await refresh(s,userId,bills);setMessage('Bills saved successfully.')}
 const status=(o:BillOccurrence)=>effectiveStatus(o),name=(o:BillOccurrence)=>bills.find(b=>b.id===o.billId)?.name??'Bill',soon=new Date();soon.setDate(soon.getDate()+7);const due=items.filter(o=>status(o)==='upcoming'&&new Date(`${o.dueDate}T12:00:00`)<=soon),overdue=items.filter(o=>status(o)==='overdue'),paid=items.filter(o=>o.status==='paid'&&o.paidAt?.slice(0,7)===today().slice(0,7)),upcoming=items.filter(o=>status(o)==='upcoming'&&!due.some(x=>x.id===o.id));
 const actions=(o:BillOccurrence)=><div className="flex gap-3 text-xs"><button onClick={()=>setDialog({item:o,amount:o.expectedAmount,date:today(),partial:false})} className="font-semibold text-cyan-300">Mark Paid</button><button onClick={()=>setDialog({item:o,amount:o.expectedAmount,date:today(),partial:true})}>Mark partial</button><button onClick={()=>change(o,{status:'skipped',paid_at:null,paid_amount:null},'Occurrence skipped.')}>Skip</button></div>;
 if(loading)return <main className="grid min-h-[70vh] place-items-center">Loading bills…</main>;
 return <main className="mx-auto max-w-7xl px-5 py-8"><header className="flex justify-between gap-4"><div><p className="text-sm text-cyan-300">Cash Flow</p><h1 className="text-4xl font-semibold">Bills</h1></div><button onClick={saveBills} className="rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950">Save bills</button></header>{message&&<p role="status" className="mt-5 rounded-xl border border-slate-700 p-4">{message}</p>}<div className="mt-6 grid gap-6 lg:grid-cols-2"><Section title="Due soon" items={due} name={name} actions={actions}/><Section title="Overdue" items={overdue} name={name} actions={actions}/><Section title="Paid this month" items={paid} name={name} actions={o=><button onClick={()=>change(o,{status:'upcoming',paid_at:null,paid_amount:null},'Payment undone.')} className="text-xs text-cyan-300">Undo payment</button>}/><Section title="Upcoming" items={upcoming} name={name} actions={actions}/></div><section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-2xl font-semibold">All recurring bills</h2><button onClick={()=>setBills(x=>[...x,{id:crypto.randomUUID(),name:'New bill',amount:0,dueDay:1,frequency:'monthly'}])} className="text-cyan-300">Add bill</button></div><div className="mt-4 space-y-3">{bills.map(b=><div key={b.id} className="grid gap-3 rounded-xl border border-slate-800 p-4 sm:grid-cols-4"><Field label="Bill" value={b.name} set={v=>setBills(x=>x.map(i=>i.id===b.id?{...i,name:v}:i))}/><Field label="Amount" type="number" value={String(b.amount)} set={v=>setBills(x=>x.map(i=>i.id===b.id?{...i,amount:Number(v)}:i))}/><Field label="Due day" type="number" value={String(b.dueDay)} set={v=>setBills(x=>x.map(i=>i.id===b.id?{...i,dueDay:Number(v)}:i))}/><label className="text-xs">Frequency<select className="field mt-1 w-full" value={b.frequency} onChange={e=>setBills(x=>x.map(i=>i.id===b.id?{...i,frequency:e.target.value}:i))}><option>weekly</option><option>monthly</option><option>quarterly</option><option>annual</option></select></label></div>)}</div></section>{dialog&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-5"><div className="w-full max-w-md rounded-3xl bg-slate-900 p-6"><h2 className="text-2xl font-semibold">{dialog.partial?'Mark partial':'Mark paid'}</h2><div className="mt-4 space-y-4"><Field label="Paid amount" type="number" value={String(dialog.amount)} set={v=>setDialog({...dialog,amount:Number(v)})}/><Field label="Paid date" type="date" value={dialog.date} set={v=>setDialog({...dialog,date:v})}/></div><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setDialog(null)}>Cancel</button><button onClick={submit} className="rounded-xl bg-cyan-400 px-4 py-2 text-slate-950">Save</button></div></div></div>}</main>}
function Section({title,items,name,actions}:{title:string;items:BillOccurrence[];name:(o:BillOccurrence)=>string;actions:(o:BillOccurrence)=>React.ReactNode}){return <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-4 space-y-3">{items.length===0&&<p className="text-sm text-slate-500">Nothing here.</p>}{items.map(o=><article key={o.id} className="rounded-xl border border-slate-800 p-4"><div className="flex justify-between"><div><p>{name(o)}</p><p className="text-xs text-slate-500">Due {o.dueDate}</p></div><p>{money.format(o.expectedAmount)}</p></div><div className="mt-3">{actions(o)}</div></article>)}</div></section>}
function Field({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="text-xs">{label}<input className="field mt-1 w-full" type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
